draw_config:
  dark_mode: true
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs:
    escape: |
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>location-exit</title>
        <path d="M22 12L18 8V11H10V13H18V16M20 18A10 10 0 1 1 20 6H17.27A8 8 0
        1 0 17.27 18Z" transform="rotate(-135)" transform-origin="center"/>
      </svg>
    alfred: |
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" height="24" width="24">
        <title>Alfred</title>
        <path d="M0 15.902c0 -1.142 1.133 -2.184 3 -2.977v-1.827c0 -4.142 4.029 -7.5 9 -7.5s9 3.358 9 7.5v1.827c1.867 0.793 3 1.835 3 2.977 0 2.485 -5.373 4.5 -12 4.5s-12 -2.015 -12 -4.5z" fill="#000000" stroke-width="1"></path>
      </svg>
    chatgpt: |
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" height="24" width="24">
        <title>Chromatic</title>
        <path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12 -12A12 12 0 0 0 12 0zm-0.006 3.43a3.372 3.372 0 0 1 3.37 3.369v2.199L9.628 5.689a4.261 4.261 0 0 0 -0.688 -0.32 3.351 3.351 0 0 1 3.053 -1.94zm-4.498 2.6c0.588 0 1.17 0.156 1.684 0.452l5.734 3.311 -2.91 1.678 -3.6 -2.076a0.46 0.46 0 0 0 -0.459 0L5.35 10.893c-0.22 0.126 -0.428 0.27 -0.621 0.433a3.349 3.349 0 0 1 -0.155 -3.61A3.385 3.385 0 0 1 7.496 6.03zm8.723 0.015a3.383 3.383 0 0 1 3.205 1.672 3.37 3.37 0 0 1 -1.235 4.6l-5.736 3.308v-3.357l3.602 -2.077a0.459 0.459 0 0 0 0.228 -0.398V6.799c0 -0.253 -0.021 -0.506 -0.064 -0.754zm-8.504 4.543v6.617c0 0.254 0.021 0.505 0.066 0.754a3.4 3.4 0 0 1 -0.285 0.012 3.383 3.383 0 0 1 -2.92 -1.684 3.343 3.343 0 0 1 -0.338 -2.555 3.342 3.342 0 0 1 1.57 -2.044l1.907 -1.1zm0.908 0 2.912 1.68v4.152a0.46 0.46 0 0 0 0.23 0.396l2.594 1.498h0.002c0.22 0.127 0.45 0.235 0.688 0.32a3.35 3.35 0 0 1 -3.055 1.938 3.373 3.373 0 0 1 -3.371 -3.367v-6.617zm10.647 2.088a3.347 3.347 0 0 1 0.154 3.611 3.372 3.372 0 0 1 -4.604 1.233l-1.908 -1.1 5.738 -3.309a4.31 4.31 0 0 0 0.62 -0.435z" fill="#000000" stroke-width="1"></path>
      </svg>
  svg_extra_style: |
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #FFD700;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

parse_config:
  zmk_additional_includes:
    - "zmk-workspace/zmk/zmk-helpers/include"
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  raw_binding_map:
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$

    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5

    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

    # Behaviors
    "&swapper": $$mdi:swap-horizontal$$
    "&both_par": $$mdi:code-parentheses$$
    "&both_brk": $$mdi:code-brackets$$
    "&both_brc": $$mdi:code-braces$$
    "&smart_shift":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:gesture-tap-hold$$

    # Shorter
    "MT_BSPC": $$mdi:backspace$$
    "WIN_CYCLE": $$mdi:arrow-u-up-left$$
    "WIN_CYCLE_REV":
      tap: $$mdi:arrow-u-down-left$$
      hold: $$mdi:apple-keyboard-command$$
    "CHATGPT": $$chatgpt$$
    "TRANSLATE": $$mdi:translate$$
    "ALFRED": $$alfred$$

    # Combos
    "&kp LG(X)": $$mdi:content-cut$$
    "&mt_copy": $$mdi:content-copy$$
    "&ht_delayed_paste": $$mdi:content-paste$$
    "&kp LG(V)": $$mdi:content-paste$$
    "&kp LG(LBKT)": $$mdi:arrow-left$$
    "&kp LG(RBKT)": $$mdi:arrow-right$$

    # Macros
    "&mac_lock": $$mdi:lock$$
    "&dot_spc": ""

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: ""
    FSLH:
      tap: "/"
      shifted: ""
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: ""
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    PERIOD: "."
    DOT: "."
    COMMA: ","
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
    N2:
      tap: 2
    N3:
      tap: 3
    N4:
      tap: 4
    N5:
      tap: 5
    N6:
      tap: 6
    N7:
      tap: 7
    N8:
      tap: 8
    N9:
      tap: 9
    N0:
      tap: 0

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RGUI: $$mdi:apple-keyboard-command$$
    PSCRN: $$mdi:printer-outline$$
    PAGE_UP:
      tap: "PgUp"
      shifted: ""
    PAGE_DOWN:
      tap: "PgDn"
      shifted: ""
    INSERT:
      tap: "Ins"
      shifted: ""

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$escape$$
    ESCAPE: $$escape$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$

    # Command +
    LG(A):
      tap: "A"
      shifted: $$mdi:apple-keyboard-command$$
    LG(S):
      tap: "S"
      shifted: $$mdi:apple-keyboard-command$$
    LG(D):
      tap: "D"
      shifted: $$mdi:apple-keyboard-command$$
    LG(F):
      tap: "F"
      shifted: $$mdi:apple-keyboard-command$$
    LG(Z):
      tap: "Z"
      shifted: $$mdi:apple-keyboard-command$$
    LG(X):
      tap: "X"
      shifted: $$mdi:apple-keyboard-command$$
    LG(C):
      tap: "C"
      shifted: $$mdi:apple-keyboard-command$$
    LG(V):
      tap: "V"
      shifted: $$mdi:apple-keyboard-command$$
    LG(W):
      tap: "W"
      shifted: $$mdi:apple-keyboard-command$$
    LG(Q):
      tap: "Q"
      shifted: $$mdi:apple-keyboard-command$$
    LG(E):
      tap: "E"
      shifted: $$mdi:apple-keyboard-command$$
    LG(R):
      tap: "R"
      shifted: $$mdi:apple-keyboard-command$$
    LG(T):
      tap: "T"
      shifted: $$mdi:apple-keyboard-command$$
    LG(G):
      tap: "G"
      shifted: $$mdi:apple-keyboard-command$$
    LG(B):
      tap: "B"
      shifted: $$mdi:apple-keyboard-command$$

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_caps: { align: top, o: 1.2 }
