manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: duckyb
      url-base: https://github.com/duckyb
    - name: urob
      url-base: https://github.com/urob
    - name: m165437
      url-base: https://github.com/M165437

    - name: efogdev
      url-base: https://github.com/efogdev
    # TODO: remove once https://github.com/M165437/nice-view-gem/pull/22 is merged
    - name: solotitan
      url-base: https://github.com/solotitan

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main

    # Shields
    - name: urchin-zmk-module
      remote: duckyb
      revision: main
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: zephyr-4.1

    # ZMK modules
    - name: zmk-adaptive-key
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-tri-state
      remote: urob
      revision: main
    - name: zmk-unicode
      remote: urob
      revision: main

    # Custom Nice!View
    # TODO: revert to m165437/main once https://github.com/M165437/nice-view-gem/pull/22 is merged
    - name: nice-view-gem
      remote: solotitan
      revision: ca8b2528d905cf668ebe3ee183d658b437a74025

  self:
    path: config
