manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: duckyb
      url-base: https://github.com/duckyb
    - name: urob
      url-base: https://github.com/urob
    - name: m165437
      url-base: https://github.com/M165437
    - name: badjeff
      url-base: https://github.com/badjeff

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main

    # Shields
    - name: urchin-zmk-module
      remote: duckyb
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: zmk-0.4

    # ZMK modules
    - name: zmk-adaptive-key
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-tri-state
      remote: urob
      revision: main
    - name: zmk-unicode
      remote: urob
      revision: main

    # Custom Nice!View
    - name: nice-view-gem
      remote: m165437
      revision: main

  self:
    path: config
